trigger:
- master
- develop 

pool:
 name: TS-Windows

variables:
  ArticleFull: '8866027201'
  ProjectID: 'MapStreamer'
  Major: '1'
  Minor: '0'

workspace:
  clean: all

# Build number format
name: $(ArticleFull).$(Major).$(Minor).$(rev:r)

steps:
- checkout: self 
  lfs: true
  clean: true 
  submodules: recursive
  persistCredentials: true

- task: GitBuildInformation@0
  displayName: 'Create build information for repository'
  inputs:
    outputFile: 'BuildInfo'
    branchFilterRegex: '^(origin\/master|origin\/release\/+)'
    branchApprovedRegex: '^(origin\/release\/+)'
  continueOnError: true

- task: set-version-variables@1
  displayName: 'Set version variables according to BuildNumber'
  inputs:
    setProductVersionVariable: true
    setMajorVariable: true
    setMinorVariable: true
    setBuildVariable: true
    setRevisionVariable: true
    failOnVersionSyntax: true
    defineCustomizedVariable: false 

- script: echo Version = $(Build_ProductVersion)
  displayName: 'Pipeline for setting component version and change history'